import type { CatalogItem } from "./catalogItem";

// GENERATED by scripts/add-ikea-products.mjs — do not edit by hand.
//
// Products added from their IKEA product pages. Every dimension here was
// measured from IKEA's own 3D model rather than read off the page, because the
// page states only an ambiguous two-number summary while the model is the
// product at its real size. That is why every row is verified.
export const IKEA_ITEMS: CatalogItem[] = [
  {
    "id": "ikea-80213074",
    "name": "MICKE Desk",
    "brand": "IKEA",
    "category": "desk",
    "priceCents": 10999,
    "productUrl": "https://www.ikea.com/us/en/p/micke-desk-white-80213074/",
    "imageUrl": "https://www.ikea.com/us/en/images/products/micke-desk-white__0736018_pe740345_s5.jpg",
    "dimensions": [
      1.05,
      0.754,
      0.501
    ],
    "modelId": null,
    "mount": "floor",
    "dominantHex": "#F2F2F0",
    "styleTags": [
      "desk",
      "white",
      "ikea"
    ],
    "measuredAxes": [
      "width",
      "height",
      "depth"
    ],
    "verified": true
  },
  {
    "id": "ikea-20522046",
    "name": "BILLY Bookcase",
    "brand": "IKEA",
    "category": "shelf",
    "priceCents": 7900,
    "productUrl": "https://www.ikea.com/us/en/p/billy-bookcase-white-20522046/",
    "imageUrl": "https://www.ikea.com/us/en/images/products/billy-bookcase-white__1590272_pe1038911_s5.jpg",
    "dimensions": [
      0.801,
      2.051,
      0.283
    ],
    "modelId": null,
    "mount": "floor",
    "dominantHex": "#F2F2F0",
    "styleTags": [
      "shelf",
      "white",
      "ikea"
    ],
    "measuredAxes": [
      "width",
      "height",
      "depth"
    ],
    "verified": true
  },
  {
    "id": "ikea-70489011",
    "name": "GLOSTAD Loveseat",
    "brand": "IKEA",
    "category": "sofa",
    "priceCents": 16900,
    "productUrl": "https://www.ikea.com/us/en/p/glostad-loveseat-knisa-dark-gray-70489011/",
    "imageUrl": "https://www.ikea.com/us/en/images/products/glostad-loveseat-knisa-dark-gray__0987398_pe817518_s5.jpg",
    "dimensions": [
      1.233,
      0.765,
      0.794
    ],
    "modelId": null,
    "mount": "floor",
    "dominantHex": "#8A8D8F",
    "styleTags": [
      "sofa",
      "gray",
      "ikea"
    ],
    "measuredAxes": [
      "width",
      "height",
      "depth"
    ],
    "verified": true
  },
  {
    "id": "ikea-60416925",
    "name": "KYRRE Stool",
    "brand": "IKEA",
    "category": "stool",
    "priceCents": 1999,
    "productUrl": "https://www.ikea.com/us/en/p/kyrre-stool-birch-60416925/",
    "imageUrl": "https://www.ikea.com/us/en/images/products/kyrre-stool-birch__1488024_pe1003293_s5.jpg",
    "dimensions": [
      0.468,
      0.452,
      0.42
    ],
    "modelId": null,
    "mount": "floor",
    "dominantHex": "#C9C6BE",
    "styleTags": [
      "stool",
      "beige, brown",
      "ikea"
    ],
    "measuredAxes": [
      "width",
      "height",
      "depth"
    ],
    "verified": true
  },
  {
    "id": "ikea-60595936",
    "name": "GLOSTAD Ottoman",
    "brand": "IKEA",
    "category": "ottoman",
    "priceCents": 5000,
    "productUrl": "https://www.ikea.com/us/en/p/glostad-ottoman-knisa-dark-gray-60595936/",
    "imageUrl": "https://www.ikea.com/us/en/images/products/glostad-ottoman-knisa-dark-gray__1235160_pe917293_s5.jpg",
    "dimensions": [
      0.679,
      0.416,
      0.58
    ],
    "modelId": null,
    "mount": "floor",
    "dominantHex": "#C9C6BE",
    "styleTags": [
      "ottoman",
      "ikea"
    ],
    "measuredAxes": [
      "width",
      "height",
      "depth"
    ],
    "verified": true
  }
];
