// GENERATED by scripts/build-catalog.mjs — do not edit by hand.
// Built 2026-09-12 from IKEA's live US storefront.
// Prices and links were real at build time; re-run before a demo to re-verify.
// Hand-authored items belong in catalog.manual.ts, which the build never touches.

import type { CatalogItem } from "./catalogItem";

export const GENERATED_ITEMS: CatalogItem[] = [
  {
    "id": "ikea-80213074",
    "name": "MICKE Desk",
    "brand": "IKEA",
    "category": "desk",
    "priceCents": 10999,
    "productUrl": "https://www.ikea.com/us/en/p/micke-desk-white-80213074/",
    "imageUrl": "https://www.ikea.com/us/en/images/products/micke-desk-white__0736018_pe740345_s5.jpg",
    "dimensions": [
      1.051,
      0.75,
      0.498
    ],
    "modelId": "abo-b07b7dkrw4",
    "mount": "floor",
    "dominantHex": "#F2F2F0",
    "styleTags": [
      "desk",
      "white",
      "ikea"
    ],
    "measuredAxes": [
      "width",
      "depth"
    ],
    "verified": false
  },
  {
    "id": "ikea-90214308",
    "name": "MICKE Desk",
    "brand": "IKEA",
    "category": "desk",
    "priceCents": 10999,
    "productUrl": "https://www.ikea.com/us/en/p/micke-desk-white-90214308/",
    "imageUrl": "https://www.ikea.com/us/en/images/products/micke-desk-white__0736020_pe740347_s5.jpg",
    "dimensions": [
      1.419,
      0.75,
      0.498
    ],
    "modelId": "abo-b075zbvzst",
    "mount": "floor",
    "dominantHex": "#F2F2F0",
    "styleTags": [
      "desk",
      "white",
      "ikea"
    ],
    "measuredAxes": [
      "width",
      "depth"
    ],
    "verified": false
  },
  {
    "id": "ikea-00473546",
    "name": "ALEX Drawer unit",
    "brand": "IKEA",
    "category": "desk",
    "priceCents": 9500,
    "productUrl": "https://www.ikea.com/us/en/p/alex-drawer-unit-white-00473546/",
    "imageUrl": "https://www.ikea.com/us/en/images/products/alex-drawer-unit-white__0977775_pe813763_s5.jpg",
    "dimensions": [
      0.359,
      0.75,
      0.699
    ],
    "modelId": "abo-b075x41rld",
    "mount": "floor",
    "dominantHex": "#F2F2F0",
    "styleTags": [
      "desk",
      "white",
      "ikea"
    ],
    "measuredAxes": [
      "width",
      "depth"
    ],
    "verified": false
  },
  {
    "id": "ikea-19445469",
    "name": "LOBERGET / MALSKÄR Swivel chair",
    "brand": "IKEA",
    "category": "chair",
    "priceCents": 5999,
    "productUrl": "https://www.ikea.com/us/en/p/loberget-malskaer-swivel-chair-white-s19445469/",
    "imageUrl": "https://www.ikea.com/us/en/images/products/loberget-malskaer-swivel-chair-white__1078458_pe857202_s5.jpg",
    "dimensions": [
      0.76,
      0.85,
      0.87
    ],
    "modelId": "abo-b075x33rzk",
    "mount": "floor",
    "dominantHex": "#F2F2F0",
    "styleTags": [
      "chair",
      "white",
      "ikea"
    ],
    "measuredAxes": [],
    "verified": false
  },
  {
    "id": "ikea-10601124",
    "name": "CENTERHALV Office chair",
    "brand": "IKEA",
    "category": "chair",
    "priceCents": 19999,
    "productUrl": "https://www.ikea.com/us/en/p/centerhalv-office-chair-black-10601124/",
    "imageUrl": "https://www.ikea.com/us/en/images/products/centerhalv-office-chair-black__1408739_pe971989_s5.jpg",
    "dimensions": [
      0.963,
      0.85,
      0.866
    ],
    "modelId": "abo-b07b4l9fhl",
    "mount": "floor",
    "dominantHex": "#2B2B2D",
    "styleTags": [
      "chair",
      "black",
      "ikea"
    ],
    "measuredAxes": [],
    "verified": false
  },
  {
    "id": "ikea-30533493",
    "name": "EKENÄSET Armchair",
    "brand": "IKEA",
    "category": "chair",
    "priceCents": 29900,
    "productUrl": "https://www.ikea.com/us/en/p/ekenaeset-armchair-kilanda-light-beige-30533493/",
    "imageUrl": "https://www.ikea.com/us/en/images/products/ekenaeset-armchair-kilanda-light-beige__1109687_pe870153_s5.jpg",
    "dimensions": [
      0.582,
      0.85,
      0.605
    ],
    "modelId": "abo-b07dbhckhy",
    "mount": "floor",
    "dominantHex": "#C9C6BE",
    "styleTags": [
      "chair",
      "beige",
      "ikea"
    ],
    "measuredAxes": [],
    "verified": false
  },
  {
    "id": "ikea-20522046",
    "name": "BILLY Bookcase",
    "brand": "IKEA",
    "category": "shelf",
    "priceCents": 7900,
    "productUrl": "https://www.ikea.com/us/en/p/billy-bookcase-white-20522046/",
    "imageUrl": "https://www.ikea.com/us/en/images/products/billy-bookcase-white__1590272_pe1038911_s5.jpg",
    "dimensions": [
      0.8,
      2.019,
      0.279
    ],
    "modelId": "abo-b075zf4s39",
    "mount": "floor",
    "dominantHex": "#F2F2F0",
    "styleTags": [
      "shelf",
      "white",
      "ikea"
    ],
    "measuredAxes": [
      "width",
      "depth",
      "height"
    ],
    "verified": false
  },
  {
    "id": "ikea-90301225",
    "name": "BRIMNES Bookcase",
    "brand": "IKEA",
    "category": "shelf",
    "priceCents": 14900,
    "productUrl": "https://www.ikea.com/us/en/p/brimnes-bookcase-white-90301225/",
    "imageUrl": "https://www.ikea.com/us/en/images/products/brimnes-bookcase-white__1590279_pe1038918_s5.jpg",
    "dimensions": [
      0.6,
      1.899,
      0.341
    ],
    "modelId": "abo-b07ppnncm2",
    "mount": "floor",
    "dominantHex": "#F2F2F0",
    "styleTags": [
      "shelf",
      "white",
      "ikea"
    ],
    "measuredAxes": [
      "width",
      "height"
    ],
    "verified": false
  },
  {
    "id": "ikea-90522043",
    "name": "BILLY Bookcase",
    "brand": "IKEA",
    "category": "shelf",
    "priceCents": 4900,
    "productUrl": "https://www.ikea.com/us/en/p/billy-bookcase-white-90522043/",
    "imageUrl": "https://www.ikea.com/us/en/images/products/billy-bookcase-white__1590306_pe1038945_s5.jpg",
    "dimensions": [
      0.8,
      1.06,
      0.279
    ],
    "modelId": "abo-b075zf4s39",
    "mount": "floor",
    "dominantHex": "#F2F2F0",
    "styleTags": [
      "shelf",
      "white",
      "ikea"
    ],
    "measuredAxes": [
      "width",
      "depth",
      "height"
    ],
    "verified": false
  },
  {
    "id": "ikea-10559281",
    "name": "STORKLINTA 6-drawer dresser",
    "brand": "IKEA",
    "category": "dresser",
    "priceCents": 22999,
    "productUrl": "https://www.ikea.com/us/en/p/storklinta-6-drawer-dresser-white-anchor-unlock-function-10559281/",
    "imageUrl": "https://www.ikea.com/us/en/images/products/storklinta-6-drawer-dresser-white-anchor-unlock-function__1590216_pe1038855_s5.jpg",
    "dimensions": [
      0.699,
      1.2,
      0.479
    ],
    "modelId": "abo-b07hsh4zr2",
    "mount": "floor",
    "dominantHex": "#F2F2F0",
    "styleTags": [
      "dresser",
      "white",
      "ikea"
    ],
    "measuredAxes": [
      "width",
      "depth",
      "height"
    ],
    "verified": false
  },
  {
    "id": "ikea-80574645",
    "name": "STORKLINTA 3-drawer dresser",
    "brand": "IKEA",
    "category": "dresser",
    "priceCents": 12999,
    "productUrl": "https://www.ikea.com/us/en/p/storklinta-3-drawer-dresser-gray-green-anchor-unlock-function-80574645/",
    "imageUrl": "https://www.ikea.com/us/en/images/products/storklinta-3-drawer-dresser-gray-green-anchor-unlock-function__1590169_pe1038809_s5.jpg",
    "dimensions": [
      0.699,
      0.749,
      0.479
    ],
    "modelId": "abo-b07hsh4zr2",
    "mount": "floor",
    "dominantHex": "#8A8D8F",
    "styleTags": [
      "dresser",
      "gray",
      "ikea"
    ],
    "measuredAxes": [
      "width",
      "depth",
      "height"
    ],
    "verified": false
  },
  {
    "id": "ikea-30561155",
    "name": "STORKLINTA Nightstand",
    "brand": "IKEA",
    "category": "nightstand",
    "priceCents": 5999,
    "productUrl": "https://www.ikea.com/us/en/p/storklinta-nightstand-white-with-1-drawer-30561155/",
    "imageUrl": "https://www.ikea.com/us/en/images/products/storklinta-nightstand-white-with-1-drawer__1283575_pe932557_s5.jpg",
    "dimensions": [
      0.4,
      0.53,
      0.479
    ],
    "modelId": "abo-b07hsky87x",
    "mount": "floor",
    "dominantHex": "#F2F2F0",
    "styleTags": [
      "nightstand",
      "white",
      "ikea"
    ],
    "measuredAxes": [
      "width",
      "depth",
      "height"
    ],
    "verified": false
  },
  {
    "id": "ikea-20569977",
    "name": "KNARREVIK Nightstand",
    "brand": "IKEA",
    "category": "nightstand",
    "priceCents": 1499,
    "productUrl": "https://www.ikea.com/us/en/p/knarrevik-nightstand-black-20569977/",
    "imageUrl": "https://www.ikea.com/us/en/images/products/knarrevik-nightstand-black__1255278_pe924478_s5.jpg",
    "dimensions": [
      0.419,
      0.521,
      0.337
    ],
    "modelId": "abo-b07nyshh9w",
    "mount": "floor",
    "dominantHex": "#2B2B2D",
    "styleTags": [
      "nightstand",
      "black",
      "ikea"
    ],
    "measuredAxes": [
      "width",
      "depth",
      "height"
    ],
    "verified": false
  },
  {
    "id": "ikea-80395248",
    "name": "NEIDEN Bed frame",
    "brand": "IKEA",
    "category": "bed",
    "priceCents": 6900,
    "productUrl": "https://www.ikea.com/us/en/p/neiden-bed-frame-pine-80395248/",
    "imageUrl": "https://www.ikea.com/us/en/images/products/neiden-bed-frame-pine__0749131_pe745500_s5.jpg",
    "dimensions": [
      1.713,
      0.95,
      2.372
    ],
    "modelId": "abo-b07b4scb6t",
    "mount": "floor",
    "dominantHex": "#D6BC8E",
    "styleTags": [
      "bed",
      "pine",
      "ikea"
    ],
    "measuredAxes": [],
    "verified": false
  },
  {
    "id": "ikea-09574367",
    "name": "MALM Bed frame",
    "brand": "IKEA",
    "category": "bed",
    "priceCents": 24900,
    "productUrl": "https://www.ikea.com/us/en/p/malm-bed-frame-dark-brown-veneer-s09574367/",
    "imageUrl": "https://www.ikea.com/us/en/images/products/malm-bed-frame-dark-brown-veneer__1364772_pe956028_s5.jpg",
    "dimensions": [
      1.712,
      0.95,
      2.372
    ],
    "modelId": "abo-b07b4w5v3c",
    "mount": "floor",
    "dominantHex": "#C9C6BE",
    "styleTags": [
      "bed",
      "ikea"
    ],
    "measuredAxes": [],
    "verified": false
  },
  {
    "id": "ikea-70489011",
    "name": "GLOSTAD Loveseat",
    "brand": "IKEA",
    "category": "sofa",
    "priceCents": 16900,
    "productUrl": "https://www.ikea.com/us/en/p/glostad-loveseat-knisa-dark-gray-70489011/",
    "imageUrl": "https://www.ikea.com/us/en/images/products/glostad-loveseat-knisa-dark-gray__1577178_pe1033002_s5.jpg",
    "dimensions": [
      2.208,
      0.85,
      0.948
    ],
    "modelId": "abo-b07b4mtfl8",
    "mount": "floor",
    "dominantHex": "#8A8D8F",
    "styleTags": [
      "sofa",
      "gray",
      "ikea"
    ],
    "measuredAxes": [],
    "verified": false
  },
  {
    "id": "ikea-80618531",
    "name": "SALTMYRAN Loveseat",
    "brand": "IKEA",
    "category": "sofa",
    "priceCents": 29900,
    "productUrl": "https://www.ikea.com/us/en/p/saltmyran-loveseat-oereryd-gray-beige-80618531/",
    "imageUrl": "https://www.ikea.com/us/en/images/products/saltmyran-loveseat-oereryd-gray-beige__1576105_pe1032229_s5.jpg",
    "dimensions": [
      3.471,
      0.85,
      1.606
    ],
    "modelId": "abo-b07cb5gsz2",
    "mount": "floor",
    "dominantHex": "#8A8D8F",
    "styleTags": [
      "sofa",
      "gray",
      "ikea"
    ],
    "measuredAxes": [],
    "verified": false
  },
  {
    "id": "ikea-40104294",
    "name": "LACK Coffee table",
    "brand": "IKEA",
    "category": "table",
    "priceCents": 2999,
    "productUrl": "https://www.ikea.com/us/en/p/lack-coffee-table-black-brown-40104294/",
    "imageUrl": "https://www.ikea.com/us/en/images/products/lack-coffee-table-black-brown__57540_pe163122_s5.jpg",
    "dimensions": [
      0.899,
      0.45,
      0.549
    ],
    "modelId": "abo-b084t9x9nn",
    "mount": "floor",
    "dominantHex": "#2B2B2D",
    "styleTags": [
      "table",
      "black",
      "ikea"
    ],
    "measuredAxes": [
      "width",
      "depth"
    ],
    "verified": false
  },
  {
    "id": "ikea-00104291",
    "name": "LACK Coffee table",
    "brand": "IKEA",
    "category": "table",
    "priceCents": 4999,
    "productUrl": "https://www.ikea.com/us/en/p/lack-coffee-table-black-brown-00104291/",
    "imageUrl": "https://www.ikea.com/us/en/images/products/lack-coffee-table-black-brown__57537_pe163119_s5.jpg",
    "dimensions": [
      1.181,
      0.45,
      0.781
    ],
    "modelId": "abo-b07nyshh9w",
    "mount": "floor",
    "dominantHex": "#2B2B2D",
    "styleTags": [
      "table",
      "black",
      "ikea"
    ],
    "measuredAxes": [
      "width",
      "depth"
    ],
    "verified": false
  },
  {
    "id": "ikea-40541421",
    "name": "HOLMERUD Side table",
    "brand": "IKEA",
    "category": "table",
    "priceCents": 5999,
    "productUrl": "https://www.ikea.com/us/en/p/holmerud-side-table-oak-effect-40541421/",
    "imageUrl": "https://www.ikea.com/us/en/images/products/holmerud-side-table-oak-effect__1193662_pe901564_s5.jpg",
    "dimensions": [
      0.8,
      0.45,
      0.311
    ],
    "modelId": "abo-b07mm5h3hx",
    "mount": "floor",
    "dominantHex": "#C8A87C",
    "styleTags": [
      "table",
      "oak",
      "ikea"
    ],
    "measuredAxes": [
      "width",
      "depth"
    ],
    "verified": false
  },
  {
    "id": "ikea-70437814",
    "name": "BARLAST Floor lamp",
    "brand": "IKEA",
    "category": "lamp",
    "priceCents": 999,
    "productUrl": "https://www.ikea.com/us/en/p/barlast-floor-lamp-black-white-70437814/",
    "imageUrl": "https://www.ikea.com/us/en/images/products/barlast-floor-lamp-black-white__0957676_pe805130_s5.jpg",
    "dimensions": [
      0.355,
      0.5,
      0.355
    ],
    "modelId": "abo-b07dbdv3fh",
    "mount": "floor",
    "dominantHex": "#F2F2F0",
    "styleTags": [
      "lamp",
      "white",
      "ikea"
    ],
    "measuredAxes": [],
    "verified": false
  },
  {
    "id": "ikea-90541536",
    "name": "ÖKENSAND Floor lamp",
    "brand": "IKEA",
    "category": "lamp",
    "priceCents": 8999,
    "productUrl": "https://www.ikea.com/us/en/p/oekensand-floor-lamp-beech-white-90541536/",
    "imageUrl": "https://www.ikea.com/us/en/images/products/oekensand-floor-lamp-beech-white__1187892_pe899535_s5.jpg",
    "dimensions": [
      0.299,
      0.5,
      0.341
    ],
    "modelId": "abo-b07hkgy4yz",
    "mount": "tabletop",
    "dominantHex": "#F2F2F0",
    "styleTags": [
      "lamp",
      "white",
      "ikea"
    ],
    "measuredAxes": [],
    "verified": false
  },
  {
    "id": "ikea-70096377",
    "name": "FADO Table lamp",
    "brand": "IKEA",
    "category": "lamp",
    "priceCents": 2999,
    "productUrl": "https://www.ikea.com/us/en/p/fado-table-lamp-white-70096377/",
    "imageUrl": "https://www.ikea.com/us/en/images/products/fado-table-lamp-white__0606976_pe682645_s5.jpg",
    "dimensions": [
      0.208,
      0.5,
      0.208
    ],
    "modelId": "abo-b07mbfd87n",
    "mount": "tabletop",
    "dominantHex": "#F2F2F0",
    "styleTags": [
      "lamp",
      "white",
      "ikea"
    ],
    "measuredAxes": [],
    "verified": false
  },
  {
    "id": "ikea-40559166",
    "name": "TIPHEDE Rug, flatwoven",
    "brand": "IKEA",
    "category": "rug",
    "priceCents": 3999,
    "productUrl": "https://www.ikea.com/us/en/p/tiphede-rug-flatwoven-natural-black-40559166/",
    "imageUrl": "https://www.ikea.com/us/en/images/products/tiphede-rug-flatwoven-natural-black__0772066_pe755879_s5.jpg",
    "dimensions": [
      2.651,
      0.01,
      1.971
    ],
    "modelId": "abo-b0735t6948",
    "mount": "floor",
    "dominantHex": "#2B2B2D",
    "styleTags": [
      "rug",
      "black",
      "ikea"
    ],
    "measuredAxes": [],
    "verified": false
  },
  {
    "id": "ikea-80635451",
    "name": "ÄRENDE Rug, high pile",
    "brand": "IKEA",
    "category": "rug",
    "priceCents": 14999,
    "productUrl": "https://www.ikea.com/us/en/p/aerende-rug-high-pile-off-white-80635451/",
    "imageUrl": "https://www.ikea.com/us/en/images/products/aerende-rug-high-pile-off-white__1495132_pe1004961_s5.jpg",
    "dimensions": [
      2.437,
      0.01,
      0.774
    ],
    "modelId": "abo-b07b4yltp5",
    "mount": "floor",
    "dominantHex": "#F2F2F0",
    "styleTags": [
      "rug",
      "white",
      "ikea"
    ],
    "measuredAxes": [],
    "verified": false
  },
  {
    "id": "ikea-90607688",
    "name": "STOENSE Rug, low pile",
    "brand": "IKEA",
    "category": "rug",
    "priceCents": 14999,
    "productUrl": "https://www.ikea.com/us/en/p/stoense-rug-low-pile-green-90607688/",
    "imageUrl": "https://www.ikea.com/us/en/images/products/stoense-rug-low-pile-green__1405714_pe970548_s5.jpg",
    "dimensions": [
      2.433,
      0.01,
      1.516
    ],
    "modelId": "abo-b07b4zr624",
    "mount": "floor",
    "dominantHex": "#4A5D4E",
    "styleTags": [
      "rug",
      "green",
      "ikea"
    ],
    "measuredAxes": [],
    "verified": false
  },
  {
    "id": "ikea-30515917",
    "name": "HOVET Mirror",
    "brand": "IKEA",
    "category": "mirror",
    "priceCents": 16999,
    "productUrl": "https://www.ikea.com/us/en/p/hovet-mirror-black-30515917/",
    "imageUrl": "https://www.ikea.com/us/en/images/products/hovet-mirror-black__1100010_pe866038_s5.jpg",
    "dimensions": [
      0.781,
      1.959,
      0.042
    ],
    "modelId": "abo-b07b8nw6gg",
    "mount": "wall",
    "dominantHex": "#2B2B2D",
    "styleTags": [
      "mirror",
      "black",
      "ikea"
    ],
    "measuredAxes": [
      "width",
      "height"
    ],
    "verified": false
  },
  {
    "id": "ikea-40597234",
    "name": "LINDBYN Mirror",
    "brand": "IKEA",
    "category": "mirror",
    "priceCents": 10999,
    "productUrl": "https://www.ikea.com/us/en/p/lindbyn-mirror-black-40597234/",
    "imageUrl": "https://www.ikea.com/us/en/images/products/lindbyn-mirror-black__1374978_pe960159_s5.jpg",
    "dimensions": [
      0.6,
      1.699,
      0.042
    ],
    "modelId": "abo-b07b8nw6gg",
    "mount": "wall",
    "dominantHex": "#2B2B2D",
    "styleTags": [
      "mirror",
      "black",
      "ikea"
    ],
    "measuredAxes": [
      "width",
      "height"
    ],
    "verified": false
  },
  {
    "id": "ikea-60416925",
    "name": "KYRRE Stool",
    "brand": "IKEA",
    "category": "stool",
    "priceCents": 1999,
    "productUrl": "https://www.ikea.com/us/en/p/kyrre-stool-birch-60416925/",
    "imageUrl": "https://www.ikea.com/us/en/images/products/kyrre-stool-birch__1488024_pe1003293_s5.jpg",
    "dimensions": [
      0.468,
      0.45,
      0.562
    ],
    "modelId": "abo-b075yp4wvq",
    "mount": "floor",
    "dominantHex": "#DFCCA8",
    "styleTags": [
      "stool",
      "birch",
      "ikea"
    ],
    "measuredAxes": [],
    "verified": false
  },
  {
    "id": "ikea-10135659",
    "name": "MARIUS Stool",
    "brand": "IKEA",
    "category": "stool",
    "priceCents": 899,
    "productUrl": "https://www.ikea.com/us/en/p/marius-stool-black-10135659/",
    "imageUrl": "https://www.ikea.com/us/en/images/products/marius-stool-black__0727386_pe735638_s5.jpg",
    "dimensions": [
      0.426,
      0.45,
      0.504
    ],
    "modelId": "abo-b07f2hnx7w",
    "mount": "floor",
    "dominantHex": "#2B2B2D",
    "styleTags": [
      "stool",
      "black",
      "ikea"
    ],
    "measuredAxes": [],
    "verified": false
  },
  {
    "id": "ikea-60595936",
    "name": "GLOSTAD Ottoman",
    "brand": "IKEA",
    "category": "ottoman",
    "priceCents": 5000,
    "productUrl": "https://www.ikea.com/us/en/p/glostad-ottoman-knisa-dark-gray-60595936/",
    "imageUrl": "https://www.ikea.com/us/en/images/products/glostad-ottoman-knisa-dark-gray__1577731_pe1033478_s5.jpg",
    "dimensions": [
      1.269,
      0.42,
      0.446
    ],
    "modelId": "abo-b07dbgv427",
    "mount": "floor",
    "dominantHex": "#8A8D8F",
    "styleTags": [
      "ottoman",
      "gray",
      "ikea"
    ],
    "measuredAxes": [],
    "verified": false
  }
];
