// GENERATED by scripts/fetch-ikea-models.mjs — do not edit by hand.
// Built 2026-09-12.
//
// IKEA's own glTF for each product, by catalog id. These are URLs, not files:
// nothing is downloaded into this repo, and /api/ikea-model fetches the bytes
// server-side because web-api.ikea.com rejects any request carrying a browser
// Origin header.
//
// URLs contain a content hash and change when IKEA updates a model, so re-run
// this if a product stops rendering.

export const IKEA_MODEL_URLS: Record<string, string> = {
  "ikea-80213074": "https://web-api.ikea.com/dimma/assets/1.2/80213074/PS01_S01_NV01/rqp3/glb_draco/29aadc618231455aa1bbae7aee44c20c-80213074_PS01_S01_NV01_RQP3_3.0.glb",
  "ikea-90214308": "https://web-api.ikea.com/dimma/assets/1.2/90214308/PS01_S01_NV01/isp3/glb_draco/90214308_PS01_S01_NV01_ISP3_2.0_2106fc81a58f4581811c292e092b1c34.glb",
  "ikea-00473546": "https://web-api.ikea.com/dimma/assets/1.2/00473546/PS01_S01_NV01/rqp3/glb_draco/24f4ca29e01a44c1b06fbe328b23d1a9-00473546_PS01_S01_NV01_RQP3_3.0.glb",
  "ikea-19445469": "https://web-api.ikea.com/dimma/assets/geomagical/19445469/PS01_S01_NV_01/simple/glb_draco/0ad184acc9e541e7a9923686a4565dba-G-19445469-59f0ac21dd84db329abf1658b515e052d4efeb0a-simple+draco.glb",
  "ikea-10601124": "https://web-api.ikea.com/dimma/assets/geomagical/10601124/PS01_S01_NV_01/simple/glb_draco/a23116459c04d44a55e0f32af442cf26-G-10601124-92fb8d216e34058bd5aef7bfe0c8e0411de9605a-simple+draco.glb",
  "ikea-30533493": "https://web-api.ikea.com/dimma/assets/geomagical/90533174/PS01_S01_NV_01/simple/glb/d22fea99b6cb9615d3c8e1e8e76eb03c-G-90533174-755c7f39e1c331314b0a5e1ccaed0e058898a21f-simple.glb",
  "ikea-20522046": "https://web-api.ikea.com/dimma/assets/1.2/20522046/PS01_S01_NV01/rqp3/glb_draco/856bc2c06b41e3dbf4176988ed50c3de-20522046_PS01_S01_NV01_RQP3_4.0.glb",
  "ikea-90301225": "https://web-api.ikea.com/dimma/assets/1.2/90301225/PS01_S01_NV01/rqp3/glb_draco/94426c963481451c84059dafb661e91f-90301225_PS01_S01_NV01_RQP3_3.0.glb",
  "ikea-90522043": "https://web-api.ikea.com/dimma/assets/1.2/90522043/PS01_S01_NV01/rqp3/glb_draco/bbddcfc7f752b32422988706fba0ecd6-90522043_PS01_S01_NV01_RQP3_4.0.glb",
  "ikea-10559281": "https://web-api.ikea.com/dimma/assets/1.2/10559281/LPT_S01_NV01/rqp3/glb_draco/da828632c83562e6db1d5fcafb5d0cea-10559281_LPT_S01_NV01_RQP3_4.0.glb",
  "ikea-80574645": "https://web-api.ikea.com/dimma/assets/1.2/80574645/LPT_S01_NV01/rqp3/glb_draco/224ede772f93a718a9f1a7fd18969786-80574645_LPT_S01_NV01_RQP3_4.0.glb",
  "ikea-30561155": "https://web-api.ikea.com/dimma/assets/1.2/30561155/LPT_S01_NV01/rqp3/glb_draco/5a3793341eb8857d5df3c84ec6f96265-30561155_LPT_S01_NV01_RQP3_4.0.glb",
  "ikea-80395248": "https://web-api.ikea.com/dimma/assets/1.2/80395248/PS01_S01_NV01/iqp3/glb_draco/2c9f299ffc3ec6a7d29b3919bc237ed3-80395248_PS01_S01_NV01_IQP3_2.0.glb",
  "ikea-09574367": "https://web-api.ikea.com/dimma/assets/geomagical/09574367/PS01_S01_NV_01/simple/glb/4b5b3763f9861adeb818ece7ab7fc4f2-G-09574367-fdb1dc86f54c4d8346f588399690f6b10d0b3965-simple.glb",
  "ikea-70489011": "https://web-api.ikea.com/dimma/assets/geomagical/50489012/PS01_S01_NV_01/simple/glb_draco/7191ec27182045c7838ac4eedb2fc9af-G-50489012-a6be54f48c4717762a60e001cb94d6b7e9a322be-simple+draco.glb",
  "ikea-80618531": "https://web-api.ikea.com/dimma/assets/geomagical/80618531/PS01_S01_NV_01/simple/glb_draco/ba32e4df8dcac411ebd70d2782b77500-G-80618531-9ea9d6e20867d7f4dfdeaef9429cec660d2216cd-simple+draco.glb",
  "ikea-40104294": "https://web-api.ikea.com/dimma/assets/1.2/40104294/PS01_S01_NV01/iqp3/glb_draco/c1ab11265f614438adbc4dbd83991b8f-40104294_PS01_S01_NV01_IQP3_2.0.glb",
  "ikea-00104291": "https://web-api.ikea.com/dimma/assets/1.2/00104291/PS01_S01_NV01/iqp3/glb_draco/41a20289f5294b9ea653b272e50b3d7a-00104291_PS01_S01_NV01_IQP3_2.0.glb",
  "ikea-40541421": "https://web-api.ikea.com/dimma/assets/1.2/40541421/PS01_S01_NV01/rqp3/glb_draco/e4c46a4a495e4c6cbd6cf568bdd90312-40541421_PS01_S01_NV01_RQP3_3.0.glb",
  "ikea-70437814": "https://web-api.ikea.com/dimma/assets/geomagical/10430368/PS01_S01_NV_01/simple/glb_draco/bf48231bd2ae4366b460ec8d7ba55da8-G-10430368-6e2afc3c1487ad95df11cd44ead0c03788c1f403-simple+draco.glb",
  "ikea-90541536": "https://web-api.ikea.com/dimma/assets/geomagical/00541526/PS01_S01_NV_01/simple/glb_draco/9934007624878dc7b5e8ef9df0782635-G-00541526-5913a19a42199508634d5a6ea524aa31e4de491e-simple+draco.glb",
  "ikea-70096377": "https://web-api.ikea.com/dimma/assets/1.2/70096377/PS01_S01_NV01/iqp3/glb_draco/1e63883096e8a98c6b51c0b3e0834756-70096377_PS01_S01_NV01_IQP3_2.0.glb",
  "ikea-40559166": "https://web-api.ikea.com/dimma/assets/geomagical/40559166/PS01_S01_NV_01/simple/glb_draco/24323d1240260ad1921767480bf538cb-G-40559166-95e08bd2c189a5aaff34f30ec9d3fd590d194763-simple+draco.glb",
  "ikea-30515917": "https://web-api.ikea.com/dimma/assets/geomagical/70515915/PS01_S01_NV_01/simple/glb/043a718d2a418c79351461ef59a65703-G-70515915-78e519a38bbcf3c4785ccd45612684b88fc132d0-simple.glb",
  "ikea-40597234": "https://web-api.ikea.com/dimma/assets/geomagical/80597232/PS01_S01_NV_01/simple/glb/b2a22096640db3855c118ea416734e1c-G-80597232-6be482f8982daf87db13f736e5fa3a77a59fd828-simple.glb",
  "ikea-60416925": "https://web-api.ikea.com/dimma/assets/1.2/60416925/PS01_S01_NV01/iqp3/glb_draco/937b975d6615421a8b1f44e7897c76d9-60416925_PS01_S01_NV01_iqp3_v1.4.11.glb",
  "ikea-10135659": "https://web-api.ikea.com/dimma/assets/1.2/10135659/PS01_S01_NV01/iqp3/glb_draco/068ea6b14ed0422087938e50a4c8a617-10135659_PS01_S01_NV01_IQP3_2.0.glb",
  "ikea-60595936": "https://web-api.ikea.com/dimma/assets/geomagical/20573286/PS01_S01_NV_01/simple/glb_draco/3dcd7a2bde1ac1b02909e3c7813da3c4-G-20573286-908e6a4d11f955b506d8d6083f8b421acd0009e0-simple+draco.glb"
};
